CREATE DATABASE IF NOT EXISTS crm_main;
CREATE DATABASE IF NOT EXISTS crm_hr;
CREATE DATABASE IF NOT EXISTS crm_support;
CREATE DATABASE IF NOT EXISTS admin_db;

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';

GRANT ALL PRIVILEGES ON crm_main.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON crm_hr.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON crm_support.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON admin_db.* TO 'root'@'%';

FLUSH PRIVILEGES;
